services:
  db:
    container_name: ownned_test_container
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5502:5432"
    tmpfs:
      - /var/lib/postgresql/data
    networks:
      - ownned_test
networks:
  ownned_test:
